services:
  consul-barbet-com:
    container_name: consul-barbet-com
    image: consul:1.15.4
    ports:
      - "8500:8500"
    volumes:
      - "./consul:/scripts"
    entrypoint: ["/scripts/entrypoint.sh"]
